config/routes.rb
Rails.application.routes.draw do
  # get 'homes/about'
  #get 'users/show'
  devise_for :users
  resources :books
  
  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:show, :index, :edit, :update]
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user

    validates :body, length: {maximum:200}
    validates :body, presence: true
    validates :title, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :corrent_user, only: [:edit, :update]
	
	def index
		@book = Book.new
		@books = Book.all
		@users = User.all
		# @user = current_user
	end
	
	def new
		# @newbook = Book.new
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
		flash[:notice] = "Book was successfully destroyed"
	end
	
	
	def show
		@book = Book.find(params[:id])
		@newbook = Book.new
		@user = User.find(@book.user_id)
	end

	def edit
		@book = Book.find(params[:id])
	end
	

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id 
		if @book.save
			redirect_to book_path(@book)
			flash[:notice] = "Book was successfully created."
		else
			@books = Book.all
			render :"index"
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to book_path(@book.id)
			flash[:notice] = "Book was successfully update"
		else
			render 'edit'
			flash[:danger] = "Book"
		end
	end
	

	private
	def book_params
		params.require(:book).permit(:title, :body)
	end

  def corrent_user
    @book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_user.html.erb
<div class='container top'>
	<div class='row'>
		<div class='col-xs-3'>
			<h2>User info</h2>
			<table class='table'>
				<tr>
					<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpg', fallback: "no_image.jpg"%>
				</tr>
				<tr>
					<th>name</th>
					<th><%= current_user.name %></th>
				</tr>
				<tr>
					<th>introduction</th>
					<th><%= current_user.introduction %></th>
				</tr>
			</table>

			<div class='row'>
				<%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
			</div>

			<h2>New book</h2>
			<%= form_for(@newbook) do |f| %>
			<h4>Title</h4>
			<%= f.text_field :title, class:"col-xs-12 book_title" %>

			<h4>Opinion</h4>
			<%= f.text_area :body , class:"col-xs-12 book_body"%>
			<%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
			<% end %>
		</div>

app/views/books/edit.html.erb
<div class="container top">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
        <%= @book.errors.count %>件のerrorが発生しました
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>

      <%= form_for @book do |f| %>
      <div class="row">
        <h4>Title</h4>
        <%= f.text_field :title, class:"col-xs-12" %>
      </div>
      <div class="row">
        <h4>Opinion</h4>
        <%= f.text_area :body, class:"col-xs-12" %>
      </div>
      <div class="row">
        <%= f.submit 'Update Book', class:"col-xs-12 btn btn-primary" %>
      </div>
      <% end %>
      <%= link_to "Show", book_path %>
      |
      <%= link_to "Back", "/books" %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div class="erro_explanation">
    <h2><%= @book.errors.count %>errors prohibited this obj form being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>

<div class='container top'>
	<div class='row'>
		<div class='col-xs-3'>
			<h2>User info</h2>
			<table class='table'>
				<tr>
					<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpg', fallback: "no_image.jpg"%>
				</tr>
				<tr>
					<th>name</th>
					<th><%= current_user.name %></th>
				</tr>
				<tr>
					<th>introduction</th>
					<th><%= current_user.introduction %></th>
				</tr>
			</table>

			<div class='row'>
				<%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
			</div>

			<h2>New book</h2>
			<%= form_for(@book) do |f| %>
			<h4>Title</h4>
			<%= f.text_field :title, class:"col-xs-12 book_title" %>

			<h4>Opinion</h4>
			<%= f.text_area :body , class:"col-xs-12 book_body"%>
			<%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
			<% end %>
		</div>

		<div class='col-xs-9'>
			<h2>Books</h2>

			<table class='table table-hover table-inverse'>
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 50, 50, format: 'jpg', fallback: "no_image.jpg"), user_path(book.user) %>
						</td>
						<td><%= link_to book.title, book_path(book) %></td>
						<td><%= book.body %></td>
					</tr>
					<% end %>

				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<%= render 'books/user' %>

		<div class="col-xs-9">
			<h2>Book detail</h2>
			<table class="table">
				<tbody>
					<tr>
						<td>
							<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpg', fallback: "no_image.jpg" %>
							<br><%= link_to @user.name, user_path(@book.user.id) %>
						</td>
						<td><%= @book.title %></td>
						<td><%= @book.body %></td>
            <% if @user.id == current_user.id %>
              <td><%= link_to 'Edit', edit_book_path(@book), class:"btn btn-success" %>
            <% end %>
            <% if @user.id == current_user.id%>
              <td>
                <%= link_to 'Destroy', book_path(@book), class: "btn btn-danger", method: :delete, data: { confirm: '本当に削除しますか？' } %>
              </td>
            <% end %>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>