config/routes.rb
Rails.application.routes.draw do
  # get 'homes/about'
  #get 'users/show'
  devise_for :users
  resources :books
  
  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:show, :index, :edit, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Newbookers</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li class="">
            <%= link_to "Home",user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
          </li>
          <li class="">
            <%= link_to 'Users',users_path, class: "glyphicon glyphicon-user users" %>
          </li>
          <li class="">
            <%= link_to 'Books', books_path(@book), class: "glyphicon glyphicon-book books"%>
          </li>
          <li class="">
            <%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout"%>
          </li>
          <% else %>
          <li class="">
            <%= link_to "Home", root_path, class: "glyphicon glyphicon-home home" %>
          </li>
          <li class="">
            <%= link_to "About", home_about_path, class: "glyphicon glyphicon-link about" %>
          </li>
          <li class="">
            <%= link_to "sign up", new_user_registration_path , class: "glyphicon glyphicon-edit sign_up" %>
          </li>
          <li class="">
            <%= link_to "login", new_user_session_path , class: "glyphicon glyphicon-log-in sign_in" %>
          </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <%= yield %>
  <footer>
    <div class='container'>
      <div class='row'>
        <div class='col-xs-3 col-xs-offset-9'>
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </div>
</body>

</html>